"""Agregar campos a Autos

Revision ID: 0436fb7a534f
Revises: 
Create Date: 2024-03-26 16:19:03.870696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0436fb7a534f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('vin', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('numero_lote', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nombre_subasta', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('localidad', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('img', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('imgventa', sa.String(length=255), nullable=True))

    with op.batch_alter_table('inversiones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inversion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inversiones', schema=None) as batch_op:
        batch_op.drop_column('fecha_inversion')

    with op.batch_alter_table('autos', schema=None) as batch_op:
        batch_op.drop_column('imgventa')
        batch_op.drop_column('img')
        batch_op.drop_column('localidad')
        batch_op.drop_column('nombre_subasta')
        batch_op.drop_column('numero_lote')
        batch_op.drop_column('vin')
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###
