"""Agregar modelo Empleado

Revision ID: 1c754609fe64
Revises: 7b7909067c4b
Create Date: 2024-12-14 12:27:07.093609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c754609fe64'
down_revision = '7b7909067c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal', sa.String(length=50), nullable=False),
    sa.Column('nombre_puesto', sa.String(length=100), nullable=False),
    sa.Column('nombre_persona', sa.String(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productos_str', sa.Text(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('posicion')
    op.drop_table('sucursal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sucursal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('posicion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sucursal_id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('departamento', sa.VARCHAR(length=100), nullable=False),
    sa.Column('encargado', sa.VARCHAR(length=100), nullable=True),
    sa.Column('disponible', sa.BOOLEAN(), nullable=True),
    sa.Column('superior_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.ForeignKeyConstraint(['superior_id'], ['posicion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pedidos')
    op.drop_table('empleados')
    # ### end Alembic commands ###
