"""Agregar nivel jerarquico a Empleado

Revision ID: 1e0b5b19f0ae
Revises: 1c754609fe64
Create Date: 2024-12-14 13:02:07.220950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0b5b19f0ae'
down_revision = '1c754609fe64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nivel_jerarquico', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.drop_column('nivel_jerarquico')

    # ### end Alembic commands ###
