"""Agregar campos a Autos

Revision ID: c875ef227b61
Revises: 0436fb7a534f
Create Date: 2024-03-26 17:59:57.407109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c875ef227b61'
down_revision = '0436fb7a534f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costoauto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_id', sa.Integer(), nullable=False),
    sa.Column('costo_adquisicion', sa.Float(), nullable=False),
    sa.Column('costo_reparacion', sa.Float(), nullable=True),
    sa.Column('costo_traslado', sa.Float(), nullable=True),
    sa.Column('costo_otros', sa.Float(), nullable=True),
    sa.Column('costo_importacion', sa.Float(), nullable=True),
    sa.Column('costo_honorarios', sa.Float(), nullable=True),
    sa.Column('costo_flete_obr', sa.Float(), nullable=True),
    sa.Column('costo_partes', sa.Float(), nullable=True),
    sa.Column('costo_carrocero', sa.Float(), nullable=True),
    sa.Column('costo_limpieza', sa.Float(), nullable=True),
    sa.Column('costo_gasolina', sa.Float(), nullable=True),
    sa.Column('costo_carlos', sa.Float(), nullable=True),
    sa.Column('costo_millas', sa.Float(), nullable=True),
    sa.Column('fecha_registro_costo', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auto_id'], ['autos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('costoauto')
    # ### end Alembic commands ###
